# Generated by Django 4.2.3 on 2023-07-19 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_rename_user_profile_alter_conversation_participants_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id_user',
        ),
    ]
