# Generated by Django 4.2.3 on 2023-07-19 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_profile_id_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id_user',
        ),
    ]
