# Generated by Django 4.2.3 on 2023-07-23 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_remove_profile_id_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
